### ISSUE TITLE
Model of AC dimmer module?

### ISSUE THREAD

**Issue by That-Dude** [JAndrassy/Regulator#4]
Amazing work, I'm inspired and currently building a simpler version using an ESP32 and EspHome.

The link to the the AC dimmer module is not working, can you tell me which model you are using?

I'm in the UK so 240VAC, single channel, handling from 200 to 3000 Watts would be ideal - do you think it could do that with a large heatsink? Or maybe I need two module and split the load between them.

**Comment by JAndrassy** [comment]
thank you.

just google robotdyn dimmer
many shops have it
here it is on Amazon https://www.amazon.com/RobotDyn-controller-control-Arduino-Raspberry/dp/B072K9P7KH
